benutzer/urls.py
from django.conf.urls import url

from . import views

app_name = 'benutzer'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^alle/$', views.listusers, name='benutzerliste'),
    url(r'^(?P<userid>[0-9]+)/$', views.showuser, name='detail'),
    url(r'^add/$', views.addbenutzer, name='add'),
    url(r'^add/(?P<mitgliedsnummer>[0-9]+)/$', views.addbenutzer, name='addmitgliedsnummer'),
]

bwinfalumni/urls.py
from django.conf.urls import include
from django.urls import re_path as url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView



urlpatterns = [
    url(r'^verein/', include('verein.urls', namespace='verein')),
    url(r'^umsaetze/', include('umsaetze.urls', namespace='umsaetze')),
    url(r'^profil/', include('profil.urls', namespace='profil')),
    url(r'^verwaltung/', include('mitgliederverwaltung.urls', namespace='mitgliederverwaltung')),
    url(r'^konto/', include('mitgliedskonto.urls', namespace='mitgliedskonto')),
    url(r'^mitgliedschaftsantrag/', include('mitgliedschaftsantrag.urls', namespace='mitgliedschaftsantrag')),
    url(r'^mailinglistenadressen/', include('mailinglistenadressen.urls', namespace='mailinglistenadressen')),
    url(r'^mitgliederkarte/', include('mitgliederkarte.urls', namespace='mitgliederkarte')),
    url(r'^mitgliederstatistik/', include('mitgliederstatistik.urls', namespace='mitgliederstatistik')),
    url(r'^kontostatistik/', include('kontostatistik.urls', namespace='kontostatistik')),
    url(r'^lastschriftmandate/', include('lastschriftmandatverwaltung.urls', namespace='lastschriftmandatverwaltung')),
    url(r'^erinnerungen/', include('erinnerungen.urls', namespace='erinnerungen')),
    url(r'^dringendes/', include('dringendes.urls', namespace='dringendes')),
    url(r'^logindaten/', include('emailbenutzername.urls', namespace='emailbenutzername')),
    url(r'^directlogin/', include('passwordlesslogin.urls', namespace='passwordlesslogin')),
    url(r'^login/', RedirectView.as_view(url='/accounts/login')),

    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(), { 'template_name': 'registration/logout.html',}, name='logout' ),
    url(r'^accounts/resetpassword/passwordsent/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^accounts/resetpassword/passwordchanged/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^accounts/', include(('django.contrib.auth.urls','auth'), namespace='auth')),
    url(r'^accounts/reset/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_reset_complete'),
    url(r'^admin/', admin.site.urls),
]



admin.site.site_header = 'BwInf-Alumni Login'

profil/urls.py
from django.urls import re_path as url

from . import views

app_name = 'profil'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sichtbarkeit/$', views.sichtbarkeit, name='sichtbarkeit'),
    url(r'^mitglieder/$', views.showallusers, name='mitgliederliste'),
    url(r'^(?P<mitgliedid>[0-9]+)/$', views.showuser, name='detail'),
]

bwinfalumni/templates/base.html
<!doctype html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}BwInf Alumni und Freunde{% endblock %}</title>
    <base target="_top">
    <style>
      body {
        font: normal 87.5%/1.4 Arial,sans-serif;
        color: #333;
      }
    </style>
</head>

<body>
    <div id="header">
        {% block header %}
        <div style="float:right; margin-right:50px;">
        {% if user.is_authenticated %}
        Eingeloggt als: <b>{{ user.username }}</b>{% if user.benutzermitglied %}, Mitgliedsnummer: <b>{{ user.benutzermitglied.mitglied.mitgliedsnummer }}</b> {% endif %}
        (<a href="{% url 'auth:logout' %}">Ausloggen</a>)
        {% else %}
        <a href="{% url 'auth:login' %}">Einloggen</a>
        {% endif %}
        </div>
        <a href="/">Zurück zur Startseite</a>
        <hr />
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <div id="footer">
        {% block footer %}

        {% if user.is_superuser or user.is_staff %}
        <hr />

        <h2>Admin-Bereich</h2>
        <p>
        <ul>
            <li><a href="{% url 'mitgliedskonto:index' %}">Mitgliederübersicht</a></li>
            <li><a href="{% url 'mitgliederverwaltung:benutzerliste' %}">Benutzerübersicht</a></li>
            <li><a href="{% url 'umsaetze:index' %}">Umsatzübersicht</a></li>
            <li><a href="{% url 'verein:index' %}">Vereinsbeschlüsse</a></li>
        </ul>
        </p>
        {% endif %}



        {% endblock %}
    </div>
</body>

<script>
if (window.top!=window.self)
{
    document.getElementById("header").style.display = "none";
    document.getElementById("footer").style.display = "none";
}
</script>
</html>

bwinfalumni/templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
Index page
{% endblock %}