bwinfalumni/urls.py
from django.conf.urls import include
from django.urls import re_path as url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView



urlpatterns = [
    url(r'^verein/', include('verein.urls', namespace='verein')),
    url(r'^umsaetze/', include('umsaetze.urls', namespace='umsaetze')),
    url(r'^profil/', include('profil.urls', namespace='profil')),
    url(r'^verwaltung/', include('mitgliederverwaltung.urls', namespace='mitgliederverwaltung')),
    url(r'^konto/', include('mitgliedskonto.urls', namespace='mitgliedskonto')),
    url(r'^mitgliedschaftsantrag/', include('mitgliedschaftsantrag.urls', namespace='mitgliedschaftsantrag')),
    url(r'^mailinglistenadressen/', include('mailinglistenadressen.urls', namespace='mailinglistenadressen')),
    url(r'^mitgliederkarte/', include('mitgliederkarte.urls', namespace='mitgliederkarte')),
    url(r'^mitgliederstatistik/', include('mitgliederstatistik.urls', namespace='mitgliederstatistik')),
    url(r'^kontostatistik/', include('kontostatistik.urls', namespace='kontostatistik')),
    url(r'^lastschriftmandate/', include('lastschriftmandatverwaltung.urls', namespace='lastschriftmandatverwaltung')),
    url(r'^erinnerungen/', include('erinnerungen.urls', namespace='erinnerungen')),
    url(r'^dringendes/', include('dringendes.urls', namespace='dringendes')),
    url(r'^logindaten/', include('emailbenutzername.urls', namespace='emailbenutzername')),
    url(r'^directlogin/', include('passwordlesslogin.urls', namespace='passwordlesslogin')),
    url(r'^login/', RedirectView.as_view(url='/accounts/login')),

    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(), { 'template_name': 'registration/logout.html',}, name='logout' ),
    url(r'^accounts/resetpassword/passwordsent/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^accounts/resetpassword/passwordchanged/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^accounts/', include(('django.contrib.auth.urls','auth'), namespace='auth')),
    url(r'^accounts/reset/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_reset_complete'),
    url(r'^admin/', admin.site.urls),
]



admin.site.site_header = 'BwInf-Alumni Login'

emailbenutzername/urls.py
from django.urls import re_path as url

from . import views

app_name = 'emailbenutzername'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^benutzername$', views.benutzername, name='benutzername'),
    url(r'^email$', views.email, name='email'),
]

profil/urls.py
from django.urls import re_path as url

from . import views

app_name = 'profil'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sichtbarkeit/$', views.sichtbarkeit, name='sichtbarkeit'),
    url(r'^mitglieder/$', views.showallusers, name='mitgliederliste'),
    url(r'^(?P<mitgliedid>[0-9]+)/$', views.showuser, name='detail'),
]

profil/models.py
from django.db import models
from mitglieder.models import Mitglied


class Sichtbarkeit(models.Model):
    mitglied = models.ForeignKey(Mitglied, on_delete=models.PROTECT)
    bereich  = models.CharField(max_length=200)
    sache    = models.CharField(max_length=200)
    
    def __str__(self):
        return str(self.mitglied.mitgliedsnummer)+ " (" + str(self.bereich) + "): " + str(self.sache)
    
    class Meta:
        db_table = "sichtbarkeit"
        verbose_name = "Sichtbarkeit"
        verbose_name_plural = "Sichtbarkeiten"

profil/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import Http404
import re

from .models import Sichtbarkeit
from benutzer.models import BenutzerMitglied
from mitglieder.models import Mitglied
from django.contrib.auth.models import User

from django import forms
from django.forms import formset_factory

from datetime import date

sichtbarkeiten   = [("alumni", "vorname"),
                    ("alumni", "nachname"),
                    ("alumni", "studienort"),
                    ("alumni", "studienfach"),
                    ("alumni", "beruf"),
                    ("alumni", "email"),
                    ("alumni", "telefon"),
                    ("alumni", "adresse"),
                    ("alumni", "mailingliste"),
                    ("bwinf", "vorname"),
                    ("bwinf", "nachname"),
                    ("bwinf", "email"),
                    ("bwinf", "telefon"),
                    ("bwinf", "adresse"),
                    ("welt", "vorname"),
                    ("welt", "nachname"),
                    ("welt", "studienort"),
                    ("welt", "studienfach"),
                    ("welt", "beruf"),
                    ("welt", "email"),
                    ("welt", "telefon"),
                    ("welt", "adresse"),
                    ("alumni", "karte"),
                    ("welt", "karte"),
                    ]



class MitgliedForm(forms.ModelForm):
    class Meta:
        model = Mitglied
        fields = ['anrede', 'strasse', 'adresszusatz', 'plz', 'stadt', 'land', 'telefon', 'beruf', 'studienort', 'studienfach']

@login_required
def index(request):
    benutzer = request.user
    try:
        mitglied = benutzer.benutzermitglied.mitglied
    except:
        raise Http404("Keine Benutzerinformationen vorhanden.")

    errormessage = ""
    successmessage = ""

    if request.method == 'POST':
        form = MitgliedForm(instance=mitglied, data=request.POST)
        if form.is_valid():
            form.save()
            successmessage = "Profil aktualisiert. Bitte überprüfe, ob deine Daten in der Mitgliederliste richtig angezeigt werden."
        else:
            errormessage = "Es sind Fehler aufgetreten."
    else:
        form = MitgliedForm(instance=mitglied)


    sichtbar = [Sichtbarkeit.objects.filter(mitglied=mitglied)
                                    .filter(bereich=sb[0])
                                    .filter(sache=sb[1])
                                    .exists() for sb in sichtbarkeiten]

    return render(request, 'profil/profil.html', {'form': form,
                                                  'mitglied': mitglied,
                                                  'benutzername': benutzer.username,
                                                  'benutzeremail': benutzer.email,
                                                  'errormessage': errormessage,
                                                  'successmessage': successmessage,
                                                  'sichtbar': sichtbar})


def showuser(request, mitgliedid):
    is_authenticated = request.user.is_authenticated
    scope = "alumni" if is_authenticated else "welt"

    mitglied = get_object_or_404(Mitglied, id__exact = mitgliedid)
    info = {}
    keine_info = True
    for sache in ["vorname", "nachname", "studienort", "studienfach", "beruf", "email", "telefon", "adresse", "karte"]:
        if sichtbar(mitglied, scope, sache):
            keine_info = False
            info[sache] = True
    if keine_info:
        raise Http404("Keine Benutzerinformationen vorhanden.")

    info['land_fett'] = mitglied.land.upper()
    info['email_sanitised'] = mitglied.email.replace("@", " [ bei ] ")
    info["mitglied"] = mitglied
    info["initiale"] = mitglied.vorname[0].upper()

    return render(request, 'profil/anzeige.html', {'info': info})

def sichtbar(mitglied, bereich, sache):
    return mitglied.sichtbarkeit_set.filter(bereich=bereich).filter(sache=sache).exists()

def showallusers(request):
    is_authenticated = request.user.is_authenticated
    scope = "alumni" if is_authenticated else "welt"

    today = date.today()
    mitglieder = Mitglied.objects.filter(beitrittsdatum__lte = today).exclude(austrittsdatum__lte = today).prefetch_related('sichtbarkeit_set').order_by('vorname')

    infos = []
    for mitglied in mitglieder:
        info = {}
        keine_info = True
        for sache in ["vorname", "nachname", "studienort", "studienfach", "beruf", "email", "telefon", "adresse", "karte"]:
            if sichtbar(mitglied, scope, sache):
                keine_info = False
                info[sache] = True
        if not keine_info:
            info["mitglied"] = mitglied
            info["initiale"] = mitglied.vorname[0].upper()
            infos.append(info)
    return render(request, 'profil/mitgliederliste.html', {'infos': infos})

class SichtbarkeitForm(forms.Form):
    sichtbarkeit = forms.BooleanField(required=False)

@login_required
def sichtbarkeit(request):
    benutzer = request.user
    try:
        mitglied = benutzer.benutzermitglied.mitglied
    except:
        raise Http404("Keine Benutzerinformationen vorhanden.")

    errormessage = ""
    successmessage = ""

    SichtbarkeitFormSet = formset_factory(SichtbarkeitForm)

    if request.method == 'POST':
        form = SichtbarkeitFormSet(data=request.POST)
        if form.is_valid():
            i = 0
            for sichtbarkeit in sichtbarkeiten:
                if Sichtbarkeit.objects.filter(mitglied=mitglied).filter(bereich=sichtbarkeit[0]).filter(sache=sichtbarkeit[1]).exists():
                    if i >= 6 and not form[i].cleaned_data["sichtbarkeit"]:
                        Sichtbarkeit.objects.filter(mitglied=mitglied).filter(bereich=sichtbarkeit[0]).filter(sache=sichtbarkeit[1]).delete()
                else:
                    if i < 6 or form[i].cleaned_data["sichtbarkeit"]:
                        neu = Sichtbarkeit.objects.create(mitglied=mitglied,
                                                          bereich=sichtbarkeit[0],
                                                          sache=sichtbarkeit[1])

                i += 1

            successmessage = "Einstellungen aktualisiert. Bitte überprüfe, ob deine Daten in der Mitgliederliste richtig angezeigt werden."
        else:
            errormessage = "Es sind Fehler aufgetreten."
    else:
        initial = [] # array of dicts with boolean value for the checkboxes
        for sichtbarkeit in sichtbarkeiten:
            initial.append({'sichtbarkeit': Sichtbarkeit.objects.filter(mitglied=mitglied)
                                                        .filter(bereich=sichtbarkeit[0])
                                                        .filter(sache=sichtbarkeit[1])
                                                        .exists()})
        form = SichtbarkeitFormSet(initial=initial)

    return render(request, 'profil/sichtbarkeit.html', {'form': form, 'mitglied': mitglied, 'errormessage': errormessage, 'successmessage': successmessage})

profil/templates/profil/anzeige.html
<h1>{% if info.vorname %}{{ info.mitglied.vorname }}{% else %}{{info.initiale }}.{% endif %}
    {% if info.nachname %}{{ info.mitglied.nachname }}{% endif %}</h1>

<table style="border:0px">
{% if info.studienort or info.studienfach %}
{% if info.mitglied.studienort or info.mitglied.studienfach %}
<tr><th>Studium:</th><td>{% if info.studienfach %}{{ info.mitglied.studienfach }}{% endif %} {% if info.studienort and info.mitglied.studienfach %} in {{ info.mitglied.studienort }}{% endif %}</td></tr>
{% endif %}{% endif %}
{% if info.beruf %}<tr><th>Beschäftigung:</th><td>{{ info.mitglied.beruf }}</td></tr>{% endif %}
{% if info.email %}<tr><th>E-Mail-Adresse:</th><td>{{ info.email_sanitised }}</td></tr>{% endif %}
{% if info.telefon %}<tr><th>Telefonnummer:</th><td>{{ info.mitglied.telefon }}</td></tr>{% endif %}
{% if info.adresse %}<tr><th>Adresse:</th><td>
{{ info.mitglied.strasse }}
{% if info.mitglied.adresszusatz %}<br />{{ info.mitglied.adresszusatz }}{% endif %}
<br />{{ info.mitglied.plz }} {{ info.mitglied.stadt }}
{% if info.mitglied.land != "Deutschland" %}<br />{{ info.land_fett }}{% endif %}
</td></tr>
{% elif info.wohnort %}<tr><th>Wohnort:</th><td>
{{ info.mitglied.plz }} {{ info.mitglied.stadt }}
{% if info.mitglied.land != "Deutschland" %}<br />{{ info.land_fett }}{% endif %}
</td></tr>
{% endif %}
</table>


<a href="javascript:history.back()">Zurück</a>

profil/templates/profil/mitgliederliste.html
{% if infos %}
  <ul>
  {% for info in infos %}
    <li><a href="{% url 'profil:detail' info.mitglied.id %}">
    {% if info.vorname %}{{ info.mitglied.vorname }}{% else %}{{info.initiale }}.{% endif %}
    {% if info.nachname %}{{ info.mitglied.nachname }}{% endif %}
    </a></li>
  {% endfor %}
  </ul>
{% else %}
  <p>Keine Mitglieder zum Anzeigen vorhanden.</p>
{% endif %}

profil/templates/profil/profil.html
{% extends "base.html" %}

{% block content %}

<style type="text/css">
.sbmatrix td, .sbmatrix th {
	border-left: 1px solid #000;
	padding: 0px 5px;
}

td.True {
    background-color: #66FF66;
}
td.True::before {
    content: "ja";
}

td.False {
    background-color: #FF6666;
}
td.False::before {
    content: "nein";
}


th:first-child {
border-left: none;
text-align:right;
}
</style>


<h1>Profil</h1>

<h2>Mitgliedsdaten</h2>

<form action="." method="post">
    {% csrf_token %}
    <table style="border:0px">
      <tr><th>Name:</th><td>{{ mitglied.vorname }} {{ mitglied.nachname }}</td></tr>
      <tr><th>Mitgliedsnummer:</th><td>{{ mitglied.mitgliedsnummer }}</td></tr>
      <tr><th>E-Mail:</th><td>{{ mitglied.email }}</td><td><a href="{% url 'emailbenutzername:email' %}" target="_self">E-Mailadresse ändern</a></td></tr>
      <tr><th></th><td>&nbsp;</td></tr>
      {{ form.as_table }}
      <tr><th></th><td><input type="submit" value="Speichern" /></td></tr>
    </table>
</form>
<p><span style="color:#080;font-weight:bold;">{{successmessage}}</span>
  <span style="color:#800;font-weight:bold;">{{errormessage}}</span></p>

<h2>Sichtbarkeit</h2>
<p><a href="sichtbarkeit/" target="_self">Sichtbarkeit ändern</a></p>
<table style="border:0px; text-align:center;border: none; border-collapse: collapse;" class="sbmatrix">
      <tr><th></th><th>Alumni</th><th>BWINF</th><th>Welt</th></tr>
      <tr>
        <th>Vorname</th>
        <td class="{{ sichtbar.0 }}"></td>
        <td class="{{ sichtbar.9 }}"></td>
        <td class="{{ sichtbar.14 }}"></td>
      </tr>
      <tr>
        <th>Nachname</th>
        <td class="{{ sichtbar.1 }}"></td>
        <td class="{{ sichtbar.10 }}"></td>
        <td class="{{ sichtbar.15 }}">
      </tr>
      <tr>
        <th>Studienort</th>
        <td class="{{ sichtbar.2 }}">
        <td></td>
        <td class="{{ sichtbar.16 }}">
      </tr>
      <tr>
        <th>Studienfach</th>
        <td class="{{ sichtbar.3 }}">
        <td></td>
        <td class="{{ sichtbar.17 }}">
      </tr>
      <tr>
        <th>Beschäftigung</th>
        <td class="{{ sichtbar.4 }}">
        <td></td>
        <td class="{{ sichtbar.18 }}">
      </tr>
      <tr>
        <th>E-Mail</th>
        <td class="{{ sichtbar.5 }}">
        <td class="{{ sichtbar.11 }}">
        <td class="{{ sichtbar.19 }}">
      </tr>
      <tr>
        <th>Telefon</th>
        <td class="{{ sichtbar.6 }}">
        <td class="{{ sichtbar.12 }}"></td>
        <td class="{{ sichtbar.20 }}"></td>
      </tr>
      <tr>
        <th>Adresse</th>
        <td class="{{ sichtbar.7 }}">
        <td class="{{ sichtbar.13 }}"></td>
        <td class="{{ sichtbar.21 }}"></td>
      </tr>
      <tr>
        <th>Mitgliederkarte</th>
        <td class="{{ sichtbar.22 }}">
        <td></td>
        <td class="{{ sichtbar.23 }}"></td>
      </tr>
      <tr>
        <th>Mailingliste</th>
        <td class="{{ sichtbar.8 }}"><td>
        </td><td>
        </td>
      </tr>
    </table>



<h2>Logindaten</h2>

<table style="border:0px">
      <tr><th>Benutzername:</th><td>{{ benutzername }}</td><td><a href="{% url 'emailbenutzername:benutzername' %}" target="_self">Benutzername ändern</a></td></tr>
      <tr><th>E-Mail:</th><td>{{ benutzeremail }}</td><td><a href="{% url 'emailbenutzername:email' %}" target="_self">E-Mailadresse ändern</a></td></tr>
      <tr><th></th><td></td><td><a href="{% url 'auth:password_change' %}" target="_self">Passwort ändern</a></td></tr>
</table>

{% endblock %}

profil/templates/profil/sichtbarkeit.html
{% extends "base.html" %}

{% block content %}

<style type="text/css">
td, th {
	border-left: 1px solid #000;
	padding: 5px 5px;
}
th:first-child {
border-left: none;
text-align:right;
}
</style>


<h1>Profil – Sichtbarkeitseinstellungen</h1>

<form action="." method="post">
    {% csrf_token %}
    {{ form.management_form }}
    <table style="border:0px; text-align:center;border: none; border-collapse: collapse;">
      <tr><th></th><th>Alumni-<br />vereins-<br />mitglieder</th><th>BWINF-<br />Geschäfts-<br />stelle<sup>1</sup></th><th>Weltweit<br />(öffentlich)</th></tr>
      <tr><th>Vorname</th><td><input type="checkbox" disabled="disabled" checked="checked"></td><td>{{ form.9.sichtbarkeit }}</td><td>{{ form.14.sichtbarkeit }}</td></tr>
      <tr><th>Nachname</th><td><input type="checkbox" disabled="disabled" checked="checked"></td><td>{{ form.10.sichtbarkeit }}</td><td>{{ form.15.sichtbarkeit }}</td></tr>
      <tr><th>Studienort</th><td><input type="checkbox" disabled="disabled" checked="checked"></td><td></td><td>{{ form.16.sichtbarkeit }}</td></tr>
      <tr><th>Studienfach</th><td><input type="checkbox" disabled="disabled" checked="checked"></td><td></td><td>{{ form.17.sichtbarkeit }}</td></tr>
      <tr><th>Beschäftigung</th><td><input type="checkbox" disabled="disabled" checked="checked"></td><td></td><td>{{ form.18.sichtbarkeit }}</td></tr>
      <tr><th>E-Mail</th><td><input type="checkbox" disabled="disabled" checked="checked"></td><td>{{ form.11.sichtbarkeit }}</td><td>{{ form.19.sichtbarkeit }}</td></tr>
      <tr><th>Telefon</th><td>{{ form.6.sichtbarkeit }}</td><td>{{ form.12.sichtbarkeit }}</td><td>{{ form.20.sichtbarkeit }}</td></tr>
      <tr><th>Adresse</th><td>{{ form.7.sichtbarkeit }}</td><td>{{ form.13.sichtbarkeit }}</td><td>{{ form.21.sichtbarkeit }}</td></tr>
      <tr><th>Mitgliederkarte<sup>2</sup></th><td>{{ form.22.sichtbarkeit }}</td><td></td><td>{{ form.23.sichtbarkeit }}</td></tr>
      <tr><th>Mailingliste</th><td>{{ form.8.sichtbarkeit }}</td><td></td><td></td></tr>
    </table>
    <input type="submit" value="Speichern" style="margin-left:10em;margin-top:2em;"  target="_self" />
</form>

<p><span style="color:#080;font-weight:bold;">{{successmessage}}</span>
  <span style="color:#800;font-weight:bold;">{{errormessage}}</span></p>

<p><sup>1</sup> Die BWINF-Geschäftsstelle nutzt die Daten einmal im Jahr, um im August die neuen Aufgaben der ersten Runde an die Vereinsmitglieder zu versenden.
  Die Aufgaben können nur versandt werden, wenn <b>Vorname</b>, <b>Nachname</b> und die <b>Adresse</b> an die Geschäftsstelle weitergegeben werden.</p>

<p><sup>2</sup> Die Karte verwendet außschließlich die Postleitzahl um eine ungefähre räumliche Übersicht über die Mitglieder zu geben.</p>


<p><a href=".." target="_self">Zurück zum Profil</a></p>



{% endblock %}