bwinfalumni/urls.py
from django.conf.urls import include
from django.urls import re_path as url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView



urlpatterns = [
    url(r'^verein/', include('verein.urls', namespace='verein')),
    url(r'^umsaetze/', include('umsaetze.urls', namespace='umsaetze')),
    url(r'^profil/', include('profil.urls', namespace='profil')),
    url(r'^verwaltung/', include('mitgliederverwaltung.urls', namespace='mitgliederverwaltung')),
    url(r'^konto/', include('mitgliedskonto.urls', namespace='mitgliedskonto')),
    url(r'^mitgliedschaftsantrag/', include('mitgliedschaftsantrag.urls', namespace='mitgliedschaftsantrag')),
    url(r'^mailinglistenadressen/', include('mailinglistenadressen.urls', namespace='mailinglistenadressen')),
    url(r'^mitgliederkarte/', include('mitgliederkarte.urls', namespace='mitgliederkarte')),
    url(r'^mitgliederstatistik/', include('mitgliederstatistik.urls', namespace='mitgliederstatistik')),
    url(r'^kontostatistik/', include('kontostatistik.urls', namespace='kontostatistik')),
    url(r'^lastschriftmandate/', include('lastschriftmandatverwaltung.urls', namespace='lastschriftmandatverwaltung')),
    url(r'^erinnerungen/', include('erinnerungen.urls', namespace='erinnerungen')),
    url(r'^dringendes/', include('dringendes.urls', namespace='dringendes')),
    url(r'^logindaten/', include('emailbenutzername.urls', namespace='emailbenutzername')),
    url(r'^directlogin/', include('passwordlesslogin.urls', namespace='passwordlesslogin')),
    url(r'^login/', RedirectView.as_view(url='/accounts/login')),

    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(), { 'template_name': 'registration/logout.html',}, name='logout' ),
    url(r'^accounts/resetpassword/passwordsent/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^accounts/resetpassword/passwordchanged/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^accounts/', include(('django.contrib.auth.urls','auth'), namespace='auth')),
    url(r'^accounts/reset/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_reset_complete'),
    url(r'^admin/', admin.site.urls),
]



admin.site.site_header = 'BwInf-Alumni Login'

mitgliedskonto/urls.py
from django.urls import re_path as url

from . import views

app_name = 'mitgliedskonto'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<mitgliedsnummer>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<mitgliedsnummer>[0-9]+)/(?P<mitgliedskontobuchungsnummer>[0-9]+)/$', views.bescheinigung, name='bescheinigung'),
    url(r'^(?P<mitgliedsnummer>[0-9]+)/(?P<mitgliedskontobuchungsnummer>[0-9]+)/create$', views.bescheinigung_erstellen, name='bescheinigung_erstellen'),
    url(r'^(?P<mitgliedsnummer>[0-9]+)/(?P<mitgliedskontobuchungsnummer>[0-9]+)/verify$', views.bescheinigung_verifizieren, name='bescheinigung_verifizieren'),
    url(r'^beitraege/$', views.beitraegeeinziehen, name='beitraege'),
    url(r'^beitraege/mailversand/(?P<templatename>\w+)/$', views.zahlungsaufforderungen, {'schulden': False}, name='beitragsmails'),
    url(r'^beitraege/mailversand/(?P<templatename>\w+)/schulden/$', views.zahlungsaufforderungen, {'schulden': True}, name='beitragsmailsschulden'),
    url(r'^add/$', views.addmitglied, name='add'),
]

profil/urls.py
from django.urls import re_path as url

from . import views

app_name = 'profil'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sichtbarkeit/$', views.sichtbarkeit, name='sichtbarkeit'),
    url(r'^mitglieder/$', views.showallusers, name='mitgliederliste'),
    url(r'^(?P<mitgliedid>[0-9]+)/$', views.showuser, name='detail'),
]

mitgliedskonto/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.mail.backends.smtp import EmailBackend
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.shortcuts import redirect, render, get_object_or_404
from django.template import loader
from django.forms import ModelForm
from django.http import HttpResponse, Http404
from django.conf import settings
from django.urls import reverse
from django import forms

from benutzer.models import BenutzerMitglied
from mitglieder.models import Mitglied, MitgliedskontoBuchung, MitgliedskontoBuchungstyp
from verein.models import Freistellungsbescheid

from datetime import date
import os.path
import json

@login_required
def index(request):
    benutzer = request.user

    if not benutzer.is_superuser and not benutzer.groups.filter(name='vorstand').exists():
        try:
            mitglied = benutzer.benutzermitglied.mitglied
        except:
            raise Http404("Keine Benutzerinformationen vorhanden.")
        return redirect(reverse('mitgliedskonto:detail', kwargs={'mitgliedsnummer':mitglied.mitgliedsnummer}))

    all_mitglieder = Mitglied.objects.order_by('mitgliedsnummer')
    return render(request, 'mitgliedskonto/mitgliederliste.html', {'mitglieder': all_mitglieder})



class MitgliedskontoBuchungForm(ModelForm):
    class Meta:
        model = MitgliedskontoBuchung
        fields = ['typ', 'cent_wert', 'kommentar', 'buchungsdatum', 'wirksam']


@login_required
def detail(request, mitgliedsnummer):
    benutzer = request.user

    if not benutzer.is_superuser and not benutzer.groups.filter(name='vorstand').exists():
        try:
            mitglied = benutzer.benutzermitglied.mitglied
        except:
            raise Http404("Keine Benutzerinformationen vorhanden.")
        if mitglied.mitgliedsnummer != int(mitgliedsnummer):
            raise Http404("Kein Zugriff (" + str(mitglied.mitgliedsnummer) + ")")

    mitglied = get_object_or_404(Mitglied, mitgliedsnummer__exact = mitgliedsnummer)

    if request.method == 'POST':
        mkbuchung = MitgliedskontoBuchungForm(request.POST)
        if mkbuchung.is_valid():
            buchung = mkbuchung.save(commit=False)
            buchung.mitglied = mitglied
            buchung.save()
            mkbuchung = MitgliedskontoBuchungForm()
    else:
        mkbuchung = MitgliedskontoBuchungForm()

    all_transactions = []
    value = 0
    for buchung in mitglied.mitgliedskontobuchung_set.all().order_by('buchungsdatum'):
        if buchung.wirksam:
            value += buchung.cent_wert
        all_transactions.append({'amount': buchung.cent_wert / 100.0,
                                 'comment': buchung.kommentar,
                                 'value': value / 100.0,
                                 'date': buchung.buchungsdatum,
                                 'type': buchung.typ.typname,
                                 'large': buchung.cent_wert >= 5000,
                                 'id': buchung.pk,
                                 'beleg_status': buchung.beleg_status,
                                 })
    return render(request, 'mitgliedskonto/mitglied.html', {'mitglied': mitglied, 'transactions': all_transactions, 'before': 0.0, 'after': value/100.0, 'form': mkbuchung})


@login_required
def bescheinigung(request, mitgliedsnummer, mitgliedskontobuchungsnummer):
    benutzer = request.user

    if not benutzer.is_superuser and not benutzer.groups.filter(name='vorstand').exists():
        try:
            mitglied = benutzer.benutzermitglied.mitglied
        except:
            raise Http404("Keine Benutzerinformationen vorhanden.")
        if mitglied.mitgliedsnummer != int(mitgliedsnummer):
            raise Http404("Kein Zugriff (" + str(mitglied.mitgliedsnummer) + ")")

    mitglied = get_object_or_404(Mitglied, mitgliedsnummer__exact = mitgliedsnummer)
    mitgliedskontobuchung = get_object_or_404(MitgliedskontoBuchung, pk = mitgliedskontobuchungsnummer)
    if mitglied != mitgliedskontobuchung.mitglied:
        raise Http404("Buchung nicht gefunden.")

    if mitgliedskontobuchung.beleg_status == "verifiziert" or (mitgliedskontobuchung.beleg_status != "" and (benutzer.is_superuser or benutzer.groups.filter(name='vorstand').exists())):
        if not os.path.isfile(settings.BWINFALUMNI_INVOICE_DIR + str(mitglied.mitgliedsnummer) + '_' + str(mitgliedskontobuchung.pk) + '.pdf'):
            raise Http404("Datei nicht vorhanden.")

        with open(settings.BWINFALUMNI_INVOICE_DIR + str(mitglied.mitgliedsnummer) + '_' + str(mitgliedskontobuchung.pk) + '.pdf', 'rb') as f:
            return HttpResponse(
                f,
                content_type='application/pdf',
                headers={
                    'Content-Disposition': f"attachment; filename={mitgliedskontobuchung.pk}.pdf",
                    'Cache-Control': 'no-cache'  # files are dynamic, prevent caching
                }
            )

    if mitgliedskontobuchung.beleg_status != "":
        raise Http404("Buchung nicht gefunden.")

    mitgliedskontobuchung.beleg_status = "angefordert"
    mitgliedskontobuchung.save()
    sende_email_an_vorstand(mitglied, mitgliedskontobuchung)

    return render(request, 'mitgliedskonto/request_spendenbescheinigung.html', {})


def sende_email_an_vorstand(mitglied, mitgliedskontobuchung):
    with open(settings.BWINFALUMNI_LOGS_DIR + 'maillog', 'a', encoding='utf8') as f:

        betrefftemplate = "Spendenbescheinigung angefordert"
        template = """Eine Spendenbescheinigung wurde angefordert

Name: {name}
Mitgliedsnummer: {mitgliedsnummer}
Betrag: {betrag} €
Buchungs-Datum: {buchungsdatum}
Buchungs-ID: {buchung}

Gehe zu https://alumni.bwinf.de/konto/{mitgliedsnummer} um die Bescheinigung zu erstellen und zu verifizieren.

"""

        data = {'name': mitglied.vorname + " " + mitglied.nachname,
                'vorname': mitglied.vorname,
                'nachname': mitglied.nachname,
                'anrede': mitglied.anrede,
                'mitgliedsnummer': mitglied.mitgliedsnummer,
                'datum': str(date.today()),
                'mitgliedsbeitrag': mitglied.beitrag_cent / 100.0,
                'email': mitglied.email,
                'betrag': mitgliedskontobuchung.cent_wert / 100.0,
                'buchungsdatum': mitgliedskontobuchung.buchungsdatum,
                'buchung': mitgliedskontobuchung.pk,
                }

        betreff = betrefftemplate.format(**data)
        text = template.format(**data)

        try:
            send_mail(betreff, text, 'vorstand@alumni.bwinf.de', ['vorstand@alumni.bwinf.de'])
            f.write("Date: " + str(date.today()) + "\n")
            f.write("To: vorstand@alumni.bwinf.de\n")
            f.write("From: vorstand@alumni.bwinf.de\n")
            f.write("Subject: " + betreff + "\n\n")
            f.write(text + "\n\n")
        except:
            f.write("ERROR: Could not send mail to: vorstand@alumni.bwinf.de (" + str(date.today()) + ": " + betreff + ")\n\n")

@login_required
@user_passes_test(lambda u: u.is_superuser or u.groups.filter(name='vorstand').exists())
def bescheinigung_erstellen(request, mitgliedsnummer, mitgliedskontobuchungsnummer):
    mitglied = get_object_or_404(Mitglied, mitgliedsnummer__exact = mitgliedsnummer)
    mitgliedskontobuchung = get_object_or_404(MitgliedskontoBuchung, pk = mitgliedskontobuchungsnummer)
    if mitglied != mitgliedskontobuchung.mitglied:
        raise Http404("Buchung nicht gefunden.")

    if mitgliedskontobuchung.beleg_status != "angefordert" and mitgliedskontobuchung.beleg_status != "erstellt" and mitgliedskontobuchung.beleg_status != "":
        raise Http404("Buchung nicht gefunden.")

    mitgliedskontobuchung.beleg_status = "erstellt"
    mitgliedskontobuchung.save()

    bescheide = Freistellungsbescheid.objects.order_by("datum").reverse()
    bescheid = bescheide[0]

    # Important: JSON-encode user controlled data here, as we will just dump them into a JSON object in the template
    return render(request, 'mitgliedskonto/create_spendenbescheinigung.html', {
        'name': json.dumps(mitglied.vorname + " " + mitglied.nachname),
        'vorname': json.dumps(mitglied.vorname),
        'nachname': json.dumps(mitglied.nachname),
        'anrede': json.dumps(mitglied.anrede),
        'adresszusatz': json.dumps(mitglied.adresszusatz),
        'strasse': json.dumps(mitglied.strasse),
        'plz': json.dumps(mitglied.plz),
        'stadt': json.dumps(mitglied.stadt),
        'mitgliedsnummer': mitglied.mitgliedsnummer,
        'datum': date.today(),
        'mitgliedsbeitrag': mitglied.beitrag_cent / 100.0,
        'betrag_cent': mitgliedskontobuchung.cent_wert,
        'buchungsdatum': mitgliedskontobuchung.buchungsdatum,
        'buchung': mitgliedskontobuchung.pk,
        'bescheid': bescheid,
    })

@login_required
@user_passes_test(lambda u: u.is_superuser or u.groups.filter(name='vorstand').exists())
def bescheinigung_verifizieren(request, mitgliedsnummer, mitgliedskontobuchungsnummer):
    mitglied = get_object_or_404(Mitglied, mitgliedsnummer__exact = mitgliedsnummer)
    mitgliedskontobuchung = get_object_or_404(MitgliedskontoBuchung, pk = mitgliedskontobuchungsnummer)
    if mitglied != mitgliedskontobuchung.mitglied:
        raise Http404("Buchung nicht gefunden.")

    if mitgliedskontobuchung.beleg_status != "erstellt":
        raise Http404("Buchung nicht gefunden.")

    if not os.path.isfile(settings.BWINFALUMNI_INVOICE_DIR + str(mitglied.mitgliedsnummer) + '_' + str(mitgliedskontobuchung.pk) + '.pdf'):
        raise Http404("Datei nicht vorhanden.")

    mitgliedskontobuchung.beleg_status = "verifiziert"
    mitgliedskontobuchung.save()
    sende_email_an_mitglied(mitglied, mitgliedskontobuchung)

    return render(request, 'mitgliedskonto/verify_spendenbescheinigung.html', {})


def sende_email_an_mitglied(mitglied, mitgliedskontobuchung):

mitgliedskonto/templates/mitgliedskonto/adddone.html
{% extends "base.html" %}

{% block content %}

<p><span style="color:#080;font-weight:bold;">{{successmessage}}</span>
  <span style="color:#800;font-weight:bold;">{{errormessage}}</span></p>

<p>
  <ul>
    <li><a href="/mitglieder/">Mitgliederübersicht</a></li>
    <li><a href="/benutzer/alle/">Benutzerübersicht</a></li>
    <li><a href="/accounts/logout/?next=/">Logout</a></li>
  </ul>
</p>

{% endblock %}

mitgliedskonto/templates/mitgliedskonto/addform.html
{% extends "base.html" %}

{% block content %}


<h1>Mitglied hinzufügen</h1>

<form action="." method="post">
    {% csrf_token %}
    <table style="border:0px">
      {{ mform.as_table }}
      {{ pform.as_table }}
      {{ bform.as_table }}
      <tr><th></th><td><input type="submit" value="Hinzufügen" /></td></tr>
    </table>
</form>

<script>
  var checkbox = document.getElementById("id_adduserp");
  
  var fields = [];
  
  fields.push(document.getElementById("id_username"));
  fields.push(document.getElementById("id_email"));

  function showall() {
    for (i in fields) {
      fields[i].required = true;
      fields[i].parentNode.parentNode.style.display = "table-row";
    }
  }
  function hideall() {
    for (i in fields) {
      fields[i].required = false;
      fields[i].parentNode.parentNode.style.display = "none";
    }
  }
  
  function togglevis(){
    if (checkbox.checked) {
      showall();
    }
    else {
      hideall();
    }
  };
  
  checkbox.onchange = togglevis;
  
  togglevis();
</script>


{% endblock %}

mitgliedskonto/templates/mitgliedskonto/beitraege.html
{% extends "base.html" %}

{% block content %}

<h1>Beiträge einziehen</h1>

<form action="." method="post">
    {% csrf_token %}
    <table style="border:0px">
      {{ bform.as_table }}
      <tr><th></th><td><input type="submit" value="Von ALLEN Mitgliedern einziehen" /></td></tr>
    </table>
</form>

{% endblock %}

mitgliedskonto/templates/mitgliedskonto/create_spendenbescheinigung.html
<h3>Spendenbescheinigung anlegen</h3>

<p>Nutze <kbd>generate.sh</kbd> im Verzeichnis <kbd>spendenbescheinigungen</kbd> vom Vorstandsrepository:<p>

<div style="max-width: 1200px; background-color: #eee;">
<kbd>
  ./generate.sh '{"name":{{ name }}, "adresse": {{ strasse }}, "adresszusatz": {{ adresszusatz }}, "plz": {{ plz }}, "ort": {{ stadt }}, "betrag_cent": {{ betrag_cent }}, "betrag_datum": "{{ buchungsdatum }}", "gem_finanzamt": "{{ bescheid.finanzamt }}", "gem_steuernummer": "{{ bescheid.steuernummer }}", "gem_datum": "{{ bescheid.datum|date:"d.m.Y" }}", "gem_zeitraum": "{{ bescheid.zeitraum }}", "unterschrift_datum": "{{ datum }}" }' '{{ mitgliedsnummer }}_{{ buchung }}.pdf'
</kbd>
</div>

<p>
Benötigt:
<ul>
  <li><kbd>uv</kbd></li>
  <li><kbd>lualatex</kbd></li>
</ul>
</p>

<p>
Anschließend "Spendenbescheinigung verizieren" klicken um die Spendenbescheinigung für das Mitglied verfügbar zu machen und automatisch eine Benachrichtigung per E-Mail an das Mitglied zu senden.
</p>

<p>
<a href="..">Zurück</a>
</p>

mitgliedskonto/templates/mitgliedskonto/email.html
{% extends "base.html" %}

{% block content %}

<h1>Beiträge einziehen</h1>

<form action="." method="post">
    {% csrf_token %}
    <table style="border:0px">
      {{ cform.as_table }}
      <tr><th></th><td><input type="submit" value="An ALLE Mitglieder {% if schulden %}mit Kontostand unter angegebenem {% endif %}senden" /></td></tr>
    </table>
</form>

{% if not schulden %}
<script>
  document.getElementById("id_schulden_betrag_cent").parentNode.parentNode.style.display = "none";
</script>
{% endif %}

<p>Folgende Variablen stehen zur Verfügung</p>
<table>
<tr><th>{vorname}</th><td>Vorname</td></tr>
<tr><th>{nachname}</th><td>Nachname</td></tr>
<tr><th>{anrede}</th><td>z. B. 'Herr' oder 'Frau'</td></tr>
<tr><th>{mitgliedsnummer}</th><td>Mitgliedsnummer</td></tr>
<tr><th>{datum}</th><td>Heute (Format '2017-07-22')</td></tr>
<tr><th>{kontostand}</th><td>Mitgliedsbeitrags-Kontostand</td></tr>
<tr><th>{schulden}</th><td>negativer Mitgliedsbeitrags-Kontostand</td></tr>
<tr><th>{email}</th><td>E-Mailadresse</td></tr>
<tr><th>{lastschrift_vorhanden}</th><td>'JA' oder 'NEIN'</td></tr>
<tr><th>{lastschrift}</th><td>Leer oder Informationen zum Lastschriftmandat inkl. Zeilenumbruch am Ende</td></tr>
</table>


{% endblock %}

mitgliedskonto/templates/mitgliedskonto/mitglied.html
{% extends "base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mitglieder/style.css' %}" />

<h1>{{ mitglied.mitgliedsnummer }}</h1>
<h2>{{ mitglied.vorname }} {{ mitglied.nachname }}</h2>

<hr>
{% load humanize %}

<style>
td, th {padding: 0px 20px;}
</style>

<h3>Umsätze:</h3>
<form action="." method="post">
  {% csrf_token %}
<table>
  <tr><th>Art</th><th>Wertstellung</th><th>Umsatz</th><th>Kontostand</th><th>Kommentar</th><th></th></tr>
  {% for transaction in transactions %}
  <tr><td>{{ transaction.type }}</td><td>{{ transaction.date }}</td><td class="ra"><b>{% if transaction.amount > 0 %}+{% endif %}{{ transaction.amount|floatformat:2 }} €</b></td><td class="ra">{{ transaction.value|floatformat:2 }} €</td><td>{{ transaction.comment }}</td><td>
      {% if transaction.large or user.is_superuser or user.is_staff or transaction.beleg_status != "" %}
        {% if transaction.beleg_status != "angefordert" and transaction.beleg_status != "erstellt" and transaction.beleg_status != "verifiziert" %}
          <a href="{{ transaction.id }}/">Spendenbescheinigung anfordern</a>
        {% endif %}
        {% if transaction.beleg_status == "angefordert" or transaction.beleg_status == "erstellt" %}
          Spendenbescheinigung wurde angefordert
        {% endif %}
        {% if user.is_superuser and transaction.beleg_status == "angefordert" or user.is_staff and transaction.beleg_status == "angefordert" or user.is_superuser and transaction.beleg_status == "erstellt" or user.is_staff and transaction.beleg_status == "erstellt" %}
          <a href="{{ transaction.id }}/create">Spendenbescheinigung erstellen</a>
        {% endif %}
        {% if user.is_superuser and transaction.beleg_status == "erstellt" or user.is_staff and transaction.beleg_status == "erstellt" %}
          <a href="{{ transaction.id }}/">Spendenbescheinigung herunterladen</a>
          <a href="{{ transaction.id }}/verify">Spendenbescheinigung verifizieren</a>
        {% endif %}
        {% if transaction.beleg_status == "verifiziert" %}
          <a href="{{ transaction.id }}/">Spendenbescheinigung herunterladen</a>
        {% endif %}
      {% endif %}
    </td></tr>
  {% endfor %}

  {% if user.is_superuser or user.is_staff %}
  <tr><td>{{ form.typ }}</td><td>{{ form.buchungsdatum }}</td><td>{{ form.cent_wert }} <b>Cent</b></td><td></td><td>{{ form.kommentar }}</td><td>{{ form.wirksam }} {{form.wirksam.label}}</td><td><input type="submit" value="Hinzufügen" /></td></tr>
<tr><td>{{ form.typ.errors }}</td><td>{{ form.buchungsdatum.errors }}</td><td>{{ form.cent_wert.errors }}</td><td></td><td>{{ form.kommentar.errors }}</td><td>{{ form.wirksam.errors }}</td></tr>
  {% endif %}
</table>
</form>
<hr>

<b>Aktueller Konstostand: {{ after|floatformat:2 }} € </b>

{% endblock %}

mitgliedskonto/templates/mitgliedskonto/mitgliederliste.html
{% extends "base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mitglieder/style.css' %}" />

<h1>Mitgliedsbeiträge</h1>
  <ul class="bl">
  <li><a href="{% url 'mitgliedskonto:beitraege' %}">Mitgliedsbeiträge einziehen</a></li>
  <li><a href="{% url 'mitgliedskonto:beitragsmails' 'beitragsrechnung' %}">Mails mit Beitragsrechnung verschicken</a></li>
  <li><a href="{% url 'mitgliedskonto:beitragsmailsschulden' 'zahlungserinnerung' %}">Mails mit Zahlungserinnerung verschicken</a></li>
</ul>

<h1>Alle Mitglieder</h1>

{% if mitglieder %}
  <ul class="bl">
  {% for mitglied in mitglieder %}
    <li><a href="{% url 'mitgliedskonto:detail' mitglied.mitgliedsnummer %}">{{ mitglied }}</a></li>
  {% endfor %}
  <li><a href="{% url 'mitgliedskonto:add' %}">+</a></li>
  </ul>
{% else %}
  <p>Keine Mitglieder vorhanden.</p>
{% endif %}

{% endblock %}

mitgliedskonto/templates/mitgliedskonto/request_spendenbescheinigung.html
{% extends "base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mitglieder/style.css' %}" />

{% load humanize %}

<h3>Spendenbescheinigung angefordert</h3>

<p>
Du erhältst eine E-Mail, sobald deine Spendenbescheinigung hier verfügbar ist.
</p>

<p>
<a href="..">Zurück</a>
</p>

{% endblock %}

mitgliedskonto/templates/mitgliedskonto/verify_spendenbescheinigung.html
<h3>Spendenbescheinigung verifiziert</h3>

<p>
<a href="..">Zurück</a>
</p>