bwinfalumni/urls.py
from django.conf.urls import include
from django.urls import re_path as url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView



urlpatterns = [
    url(r'^verein/', include('verein.urls', namespace='verein')),
    url(r'^umsaetze/', include('umsaetze.urls', namespace='umsaetze')),
    url(r'^profil/', include('profil.urls', namespace='profil')),
    url(r'^verwaltung/', include('mitgliederverwaltung.urls', namespace='mitgliederverwaltung')),
    url(r'^konto/', include('mitgliedskonto.urls', namespace='mitgliedskonto')),
    url(r'^mitgliedschaftsantrag/', include('mitgliedschaftsantrag.urls', namespace='mitgliedschaftsantrag')),
    url(r'^mailinglistenadressen/', include('mailinglistenadressen.urls', namespace='mailinglistenadressen')),
    url(r'^mitgliederkarte/', include('mitgliederkarte.urls', namespace='mitgliederkarte')),
    url(r'^mitgliederstatistik/', include('mitgliederstatistik.urls', namespace='mitgliederstatistik')),
    url(r'^kontostatistik/', include('kontostatistik.urls', namespace='kontostatistik')),
    url(r'^lastschriftmandate/', include('lastschriftmandatverwaltung.urls', namespace='lastschriftmandatverwaltung')),
    url(r'^erinnerungen/', include('erinnerungen.urls', namespace='erinnerungen')),
    url(r'^dringendes/', include('dringendes.urls', namespace='dringendes')),
    url(r'^logindaten/', include('emailbenutzername.urls', namespace='emailbenutzername')),
    url(r'^directlogin/', include('passwordlesslogin.urls', namespace='passwordlesslogin')),
    url(r'^login/', RedirectView.as_view(url='/accounts/login')),

    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(), { 'template_name': 'registration/logout.html',}, name='logout' ),
    url(r'^accounts/resetpassword/passwordsent/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^accounts/resetpassword/passwordchanged/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^accounts/', include(('django.contrib.auth.urls','auth'), namespace='auth')),
    url(r'^accounts/reset/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_reset_complete'),
    url(r'^admin/', admin.site.urls),
]



admin.site.site_header = 'BwInf-Alumni Login'

mitgliedschaftsantrag/urls.py
from django.urls import re_path as url

from . import views

app_name = 'mitgliedschaftsantrag'

urlpatterns = [
    url(r'^$', views.neuerantrag, name='neuerantrag'),
    url(r'^liste$', views.liste, name='liste'),
    url(r'^neu$', views.neuemitgliedschaft, name='neuemitgliedschaft'),
    url(r'^verifiziere/$', views.verifikation, name='verifikation'),
    url(r'^verifiziere/(?P<code>[-a-zA-Z0-9_]+)$', views.verifikation, name='verifikationparam'),
    url(r'^abschluss/(?P<mitgliedsnummer>[0-9]+)/$', views.zahlungsinformationen, name='zahlungsinformationen'),
    url(r'^antrag/(?P<mitgliedsnummer>[0-9]+)/$', views.antrag, name='antrag'),
]

profil/urls.py
from django.urls import re_path as url

from . import views

app_name = 'profil'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sichtbarkeit/$', views.sichtbarkeit, name='sichtbarkeit'),
    url(r'^mitglieder/$', views.showallusers, name='mitgliederliste'),
    url(r'^(?P<mitgliedid>[0-9]+)/$', views.showuser, name='detail'),
]

mitgliedschaftsantrag/models.py
from django.db import models
from datetime import date

class Mitgliedschaftsantrag(models.Model):

    MS_ARTEN = [
        ('O', 'Ordentliches Mitglied'),
        ('F', 'Fördermitglied'),
    ]

    mitgliedschaft    = models.CharField(max_length=2, choices=MS_ARTEN, default='O')
    mitgliedsbeitrag  = models.IntegerField(default=50)
    antragsdatum      = models.DateField(default=date.today)

    vorname           = models.CharField(max_length=250)
    nachname          = models.CharField(max_length=250)
    anrede            = models.CharField(max_length=250, blank=True)
    geburtsdatum      = models.DateField()

    strasse           = models.CharField(max_length=250)
    adresszusatz      = models.CharField(max_length=250, blank=True)
    plz               = models.CharField(max_length=10)
    stadt             = models.CharField(max_length=250)
    land              = models.CharField(max_length=250, default="Deutschland")
    telefon           = models.CharField(max_length=250, blank=True)
    email             = models.EmailField()
    verifikationscode = models.CharField(max_length=250)
    beruf             = models.CharField(max_length=250, blank=True)

    studienort        = models.CharField(max_length=250, blank=True)
    studienfach       = models.CharField(max_length=250, blank=True)

    mailingliste      = models.BooleanField()
    adresse_verein    = models.BooleanField()
    adresse_bwinf     = models.BooleanField()
    name_welt         = models.BooleanField()

    def __str__(self):
        return str(self.antragsdatum)+ ": " + self.vorname + " " + self.nachname + " (" + self.verifikationscode + "), Beitrag " + str(self.mitgliedsbeitrag) + " Euro"

    class Meta:
        db_table = "mitgliedschaftsantrag"
        verbose_name = "Mitgliedschaftsantrag"
        verbose_name_plural = "Mitgliedschaftsanträge"

mitgliedschaftsantrag/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.urls import reverse
from django import forms

from .models import Mitgliedschaftsantrag
from profil.models import Sichtbarkeit
from benutzer.models import BenutzerMitglied
from mitglieder.models import Mitglied, MitgliedskontoBuchung, MitgliedskontoBuchungstyp
from verein.models import Verein

from datetime import date
from random import choice

class MitgliedschaftsantragForm(forms.ModelForm):
    class Meta:
        model = Mitgliedschaftsantrag
        fields = ['vorname', 'nachname', 'anrede', 'geburtsdatum', 'email', 'mitgliedschaft', 'mitgliedsbeitrag', 'strasse', 'adresszusatz', 'plz', 'stadt', 'land', 'telefon', 'beruf', 'studienort', 'studienfach', 'mailingliste', 'adresse_verein', 'adresse_bwinf', 'name_welt']
        widgets = { 'mitgliedschaft': forms.RadioSelect }
        labels = {
            'vorname': "Vorname*",
            'nachname': "Nachname*",
            'geburtsdatum': "Geburtsdatum*",
            'email': "E-Mailadresse*",
            'mitgliedschaft': "Vereinsmitgliedschaft*",
            'strasse': "Straße, Hausnummer*",
            'plz': "Postleitzahl*",
            'stadt': "Ort*",

            'beruf': "Beschäftigung" }

def neuerantrag(request):
    errormessage = ""
    successmessage = ""

    beschluesse = Verein.objects.filter(mitgliedsbeitrag_cent__isnull=False).order_by("beschlussfassung").reverse()
    default_mitgliedsbeitrag = int(beschluesse[0].mitgliedsbeitrag_cent / 100)


    if request.method == 'POST':
        form = MitgliedschaftsantragForm(data=request.POST)
        if form.is_valid():
            ma = form.save(commit=False)
            ma.verifikationscode = ''.join(choice("ABCDEFGHKMNPQRSTUVWXYZ23456789") for _ in range(8))
            if ma.mitgliedschaft == 'O' or ma.mitgliedsbeitrag >= 50:
                if ma.mitgliedschaft == 'O':
                    ma.mitgliedsbeitrag = default_mitgliedsbeitrag
                sende_email_mit_verifikationscode(ma)
                ma.save()
                return redirect('mitgliedschaftsantrag:verifikation')
            else:
                errormessage = "Für Fördermitglieder soll der Mitgliedsbeitrag 50 € nicht unterschreiten."
        else:
            errormessage = "Es sind Fehler aufgetreten. (S. o.)"
    else:
        form = MitgliedschaftsantragForm()

    isadmin = request.user.is_superuser or request.user.groups.filter(name='vorstand').exists()

    return render(request,
                  'mitgliedschaftsantrag/antrag.html',
                  {'form': form,
                   'mitgliedsbeitrag': default_mitgliedsbeitrag,
                   'isadmin': isadmin,
                   'errormessage': errormessage,
                   'successmessage': successmessage,
                  })


@login_required
@user_passes_test(lambda u: u.is_superuser or u.groups.filter(name='vorstand').exists())
def liste(request):
    verifikationen = []
    for ma in Mitgliedschaftsantrag.objects.all():
        verifikationen.append({
            "id": ma.id,
            "name": ma.vorname + " " + ma.nachname,
            "datum": ma.antragsdatum,
            "code": ma.verifikationscode,
            "email": ma.email,
        })
    antraege = []
    for m in Mitglied.objects.filter(beitrittsdatum__isnull=True):
        antraege.append({
            "id": m.id,
            "mitgliedsnummer": m.mitgliedsnummer,
            "name": m.vorname + " " + m.nachname,
            "datum": m.antragsdatum,
        })

    return render(request, 'mitgliedschaftsantrag/liste.html',
                  {'verifikationen': verifikationen,
                   'antraege': antraege,
                  })


class MitgliedForm(forms.ModelForm):
    beitrag              = forms.BooleanField(required=False)
    beitrag_text         = forms.CharField(required=False)
    gutschrift           = forms.BooleanField(required=False)
    gutschrift_text      = forms.CharField(required=False)
    gutschrift_wert_cent = forms.IntegerField(required=False)
    mail                 = forms.BooleanField(required=False)

    sichtbarkeit_mailingliste   = forms.BooleanField(required=False)
    sichtbarkeit_adresse_verein = forms.BooleanField(required=False)
    sichtbarkeit_adresse_bwinf  = forms.BooleanField(required=False)
    sichtbarkeit_name_welt      = forms.BooleanField(required=False)

    class Meta:
        model = Mitglied
        exclude = ["austrittsdatum", "mitgliedsnummer", "anzahl_mahnungen"]


@login_required
@user_passes_test(lambda u: u.is_superuser or u.groups.filter(name='vorstand').exists())
def neuemitgliedschaft(request):
    errormessage = ""
    successmessage = ""

    if request.method == 'POST':
        form = MitgliedForm(data=request.POST)
        if form.is_valid():
            mitgliedsnummer = Mitglied.objects.order_by('-mitgliedsnummer')[0].mitgliedsnummer + 1
            m = form.save(commit=False)
            m.mitgliedsnummer = mitgliedsnummer
            m.save()

            setze_sichtbarkeiten(m,
                                 form.cleaned_data['sichtbarkeit_mailingliste'],
                                 form.cleaned_data['sichtbarkeit_adresse_verein'],
                                 form.cleaned_data['sichtbarkeit_adresse_bwinf'],
                                 form.cleaned_data['sichtbarkeit_name_welt'])

            if form.cleaned_data['mail']:
                if m.beitrittsdatum == None:
                    sende_email_mit_zahlungsinformationen(m)
                else:
                    benutzername = "m" + str(m.mitgliedsnummer)
                    passwort = ''.join(choice("ABCDEFGHKMNPQRSTUVWXYZabcdefghkmnpqrstuvwxyz23456789") for _ in range(16))
                    benutzer = User.objects.create_user(username=benutzername, email=m.email, password=passwort)
                    benutzermitglied = BenutzerMitglied(benutzer=benutzer, mitglied=m)
                    benutzermitglied.save()
                    sende_email_mit_zugangsdaten(m, passwort, benutzername)
            sende_email_an_vorstand(m, m.beitrittsdatum != None)

            if form.cleaned_data['beitrag']:
                try:
                    typ = MitgliedskontoBuchungstyp.objects.filter(typname="Mitgliedsbeitrag")[0]
                except:
                    typ = MitgliedskontoBuchungstyp.objects.create(typname="Mitgliedsbeitrag")
                MitgliedskontoBuchung.objects.create(mitglied=m, typ=typ, cent_wert=-m.beitrag_cent, kommentar=form.cleaned_data['beitrag_text'])

            if form.cleaned_data['gutschrift']:
                try:
                    typ = MitgliedskontoBuchungstyp.objects.filter(typname="Gutschrift")[0]
                except:
                    typ = MitgliedskontoBuchungstyp.objects.create(typname="Gutschrift")
                MitgliedskontoBuchung.objects.create(mitglied=m, typ=typ, cent_wert=form.cleaned_data['gutschrift_wert_cent'], kommentar=form.cleaned_data['gutschrift_text'])

            return redirect('mitgliedschaftsantrag:neuerantrag')
        else:
            errormessage = "Es sind Fehler aufgetreten. (S. o.)"
    else:
        form = MitgliedForm(initial={'beitrag': True,
                                     'beitrag_text': "Mitgliedsbeitrag " + str(date.today().year),
                                     'gutschrift_text': "Gutschrift Endrundenteilnahme (Endrunde " + str(date.today().year) + ")",
                                     'gutschrift_wert_cent': 2000,
                                     'mail': True})

    return render(request, 'mitgliedschaftsantrag/mitgliedschaft.html',
                  {'form': form,
                   'errormessage': errormessage,
                   'successmessage': successmessage,
                  })


class VerifikationForm(forms.Form):
    code = forms.CharField(label='Verifikationscode', max_length=250)

def verifikation(request, code=None):
    errormessage = ""
    successmessage = ""

    if request.method == 'POST':
        form = VerifikationForm(data=request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
        else:
            errormessage = "Es sind Fehler aufgetreten."
    else:
        form = VerifikationForm()

    if code != None:
        try:
            ma = Mitgliedschaftsantrag.objects.get(verifikationscode = code)
            m = vorlaeufiges_mitglied(ma)
            sende_email_mit_zahlungsinformationen(m)
            sende_email_an_vorstand(m, False)
            m.save()
            setze_sichtbarkeiten_antrag(m, ma)
            ma.delete()
            return redirect(reverse('mitgliedschaftsantrag:zahlungsinformationen', kwargs={'mitgliedsnummer':m.mitgliedsnummer}))
        except ObjectDoesNotExist: # Kein Mitgliedschaftsantrag mit diesem Code vorhanden
            errormessage = "Dieser Code ist nicht gültig. Möglicherweise wurde die E-Mailadresse bereits erfolgreich verifiziert."

    return render(request, 'mitgliedschaftsantrag/verifikation.html',
                  {'form': form,
                   'errormessage': errormessage,
                   'successmessage': successmessage,
                  })

def zahlungsinformationen(request, mitgliedsnummer):
    # 404 wenn Mitgliedschaft schon bestätigt, damit keine Beitragsinformationen extrahiert werden können.
    mitglied = get_object_or_404(Mitglied, mitgliedsnummer__exact = mitgliedsnummer, beitrittsdatum__exact = None)

    return render(request, 'mitgliedschaftsantrag/zahlungsinformationen.html',
                  {'mitgliedsnummer': mitglied.mitgliedsnummer,
                   'mitgliedsbeitrag': mitglied.beitrag_cent / 100.0,
                  })

class BeitragForm(forms.Form):

mitgliedschaftsantrag/templates/mitgliedschaftsantrag/antrag.html
{% if isadmin %}

<h1>Admin</h1>

<p><a href="{% url 'mitgliedschaftsantrag:liste' %}">Offene Mitgliedsanträge anzeigen</a></p>
<p><a href="{% url 'mitgliedschaftsantrag:neuemitgliedschaft' %}">Neues Mitglied direkt eintragen</a></p>

{% endif %}

<h1>Mitgliedschaftsantrag</h1>

<form action="." method="post">
    {% csrf_token %}

      <p>Ja, ich will Mitglied im „Bundeswettbewerb Informatik Alumni und Freunde e. V.“ werden:</p>

      <style>
        input[type=text], input[type=email] {
            margin-right: 30px;
        }
        #id_anrede, #id_plz {
            width: 100px;
        }
        #id_strasse {
            width: 300px;
        }
        #id_mitgliedschaft li {
            display: inline;
        }

      </style>

      <table>
        <tr>
          <td>{{ form.anrede.label_tag }} <br /> {{ form.anrede }} <br /> {{ form.anrede.errors }} </td>
          <td>{{ form.vorname.label_tag }} <br /> {{ form.vorname }} <br /> {{ form.vorname.errors }}</td>
          <td>{{ form.nachname.label_tag }} <br /> {{ form.nachname }} <br /> {{ form.nachname.errors }}</td>
        </tr>
      </table>
      <table>
        <tr>
          <td>{{ form.strasse.label_tag }} <br /> {{ form.strasse }} <br /> {{ form.strasse.errors }}</td>
          <td>{{ form.adresszusatz.label_tag }} <br /> {{ form.adresszusatz }} <br /> {{ form.adresszusatz.errors }}</td>
      </tr>
      </table>
      <table>
        <tr>
          <td>{{ form.plz.label_tag }} <br /> {{ form.plz }} <br /> {{ form.plz.errors }}</td>
          <td>{{ form.stadt.label_tag }} <br /> {{ form.stadt }} <br /> {{ form.stadt.errors }}</td>
          <td>{{ form.land.label_tag }} <br /> {{ form.land }} <br /> {{ form.land.errors }}</td>
      </tr>
      </table>
      <table>
        <tr>
          <td>{{ form.email.label_tag }} <br /> {{ form.email }} <br /> {{ form.email.errors }}</td>
          <td>{{ form.telefon.label_tag }} <br /> {{ form.telefon }} <br /> {{ form.telefon.errors }}</td>
          <td>{{ form.geburtsdatum.label_tag }} <br /> {{ form.geburtsdatum }} <br /> {{ form.geburtsdatum.errors }}</td>
      </tr>
      </table>


      <h4>Mitgliedschaft und Beitragshöhe</h4>

      <p>
      Der Mitgliedsbeitrag beträgt für ordentliche Mitglieder zur Zeit {{mitgliedsbeitrag}} € pro Jahr. Fördermitglieder bestimmen ihren Beitrag selber, dieser sollte aber 50 € pro Jahr nicht unterschreiten.
      </p>

      <p>
      {{ form.mitgliedschaft.label_tag }} &nbsp; {{ form.mitgliedschaft }} {{ form.mitgliedschaft.errors }}
      <span id="mitgliedsbeitrag_hide">{{ form.mitgliedsbeitrag.label_tag }} &nbsp; € {{ form.mitgliedsbeitrag }} &nbsp; </span>{{ form.mitgliedsbeitrag.errors }}
      <script>
        var mbh = document.getElementById("mitgliedsbeitrag_hide");
        var rb0 = document.getElementById("id_mitgliedschaft_0");
        var rb1 = document.getElementById("id_mitgliedschaft_1");

        function change_hide() {
          if (rb1.checked) {
            mbh.style.visibility = "";
          } else {
            mbh.style.visibility = "hidden";
          }
        }
        change_hide();

        rb0.onclick = change_hide;
        rb1.onclick = change_hide;
      </script>


      <h4>Informationen für andere Vereinsmitglieder</h4>

      <table>
        <tr>
          <td>{{ form.beruf.label_tag }} <br /> {{ form.beruf }} <br /> {{ form.beruf.errors }}</td>
          <td>{{ form.studienort.label_tag }} <br /> {{ form.studienort }} <br /> {{ form.studienort.errors }}</td>
          <td>{{ form.studienfach.label_tag }} <br /> {{ form.studienfach }} <br /> {{ form.studienfach.errors }}</td>
      </tr>
      </table>


      <h4>Häufig genutzte Voreinstellungen zu persönlichen Daten</h4>
            <p>Die Angaben zur Anzeige und Weitergabe der einzelnen persönlichen Daten können bei Wunsch nach Aufnahme in den Verein noch genauer eingestellt werden.</p>

    <p>
      {{ form.mailingliste }} <label for="{{ form.mailingliste.id_for_label }}">Ich möchte in die Mailingliste aufgenommen werden, um mich mit anderen Vereinsmitgliedern austauschen zu können. (Empfohlen; zur Zeit nur wenig Traffic.)</label> &nbsp; {{ form.mailingliste.errors }}
      <p>
      {{ form.adresse_verein }} <label for="{{ form.adresse_verein.id_for_label }}">Ich möchte meine Adresse und meine Telenfonnummer auch anderen Vereinsmitgliedern anzeigen lassen.</label> &nbsp; {{ form.adresse_verein.errors }}
      <p>
      {{ form.adresse_bwinf }} <label for="{{ form.adresse_bwinf.id_for_label }}">Ich möchte meine Adresse vom Verein an die BWINF-Geschäftsstelle weitergeben lassen. (Für den Versand der aktuellen Aufgaben des Bundeswettbewerb Informatik und Anfragen an Vereinsmitglieder.)</label> &nbsp; {{ form.adresse_bwinf.errors }}
      <p>
      {{ form.name_welt }} <label for="{{ form.name_welt.id_for_label }}">Ich möchte in den öffentlich einsehbaren Mitgliederliste aufgeführt werden. (Alle Mitglieder werden in der vereinsinternen Mitgliederliste aufgeführt.)</label> &nbsp; {{ form.name_welt.errors }}
      </p>

      <p>
      <input type="submit" value="Abschicken!" />
      </p>
</form>
<p><span style="color:#080;font-weight:bold;">{{successmessage}}</span>
  <span style="color:#800;font-weight:bold;">{{errormessage}}</span></p>

mitgliedschaftsantrag/templates/mitgliedschaftsantrag/liste.html
{% if antraege %}
<h1>Offene Anträge</h1>
<table>
  <tr><th>Datum</th><th>Mitgliedsnummer</th><th>Name</th><th>Bestätigen und Zugangsdaten zusenden</th></tr>
  {% for antrag in antraege %}
  <tr><td>{{antrag.datum}}</td><td>{{antrag.mitgliedsnummer}}</td><td>{{antrag.name}}</td><td><a href="antrag/{{antrag.mitgliedsnummer}}">Antrag ansehen<a></td></tr>
  {% endfor %}
</table>
{% endif %}


{% if verifikationen %}
<h1>Offene E-Mailverifikationen</h1>
<a href="verifiziere/">Verifizierungsseite</a>
<table>
  <tr><th>Datum</th><th>Name</th><th>E-Mail</th><th>Code</th></tr>
    {% for veri in verifikationen %}
    <tr><td>{{veri.datum}}</td><td>{{veri.name}}</td><td>{{veri.email}}</td><td>{{veri.code}}</td></tr>
    {% endfor %}
</table>
{% endif %}

mitgliedschaftsantrag/templates/mitgliedschaftsantrag/mitgliedschaft.html
<h1>Neue Mitgliedschaft eintragen</h1>

Beitrittsdatum leer lassen um Antrag zu erzeugen!

<form action="" method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="Eintragen!" />
</form>

mitgliedschaftsantrag/templates/mitgliedschaftsantrag/showantrag.html
<h1>Antrag {{antrag.mitgliedsnummer}}: {{antrag.name}}</h1>

<p>Antragsdatum: {{antrag.datum}}</p>
<p>Mitgliedsnummer: {{antrag.mitgliedsnummer}}</p>
<p>Name: {{antrag.name}}</p>

<p>Beitrag (in Cent): {{antrag.beitrag_cent}}</p>

<p>Angegebene Daten:<br />
Vorname: {{antrag.vorname}}<br />
Nachname: {{antrag.nachname}}<br />
Anrede: {{antrag.anrede}}<br />
Geburtsdatum: {{antrag.geburtsdatum}}<br />
Strasse: {{antrag.strasse}}<br />
Adresszusatz: {{antrag.adresszusatz}}<br />
PLZ: {{antrag.plz}}<br />
Stadt: {{antrag.stadt}}<br />
Land: {{antrag.land}}<br />
Telefon: {{antrag.telefon}}<br />
E-Mail: {{antrag.email}}<br />
Beruf: {{antrag.beruf}}<br />
Studienort: {{antrag.studienort}}<br />
Studienfach: {{antrag.studienfach}}<br />
</p>




<p>
  <form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zahlungseingang bestätigen &amp; Mitglied aufnehmen" />
  </form>
</p>
<p><span style="color:#800;font-weight:bold;">{{errormessage}}</span></p>

mitgliedschaftsantrag/templates/mitgliedschaftsantrag/verifikation.html
<h1>E-Mailverifikation</h1>

<p><span style="color:#080;font-weight:bold;">{{successmessage}}</span>
  <span style="color:#800;font-weight:bold;">{{errormessage}}</span></p>

<form action="." method="post">
    {% csrf_token %}
      <p>Eine E-Mail wurde zur Verfikation  an die von Ihnen angebenene E-Mailadresse gesendet.</p>
    
      <p>Bitte geben Sie ihren Verifikationscode an, der an Ihre E-Mailadresse gesendet wurde:</p>
      
      {{ form.as_p }} 
      
      <p>
      <input type="submit" value="Verifizieren!" />
      </p>
</form>

mitgliedschaftsantrag/templates/mitgliedschaftsantrag/zahlungsinformationen.html
<h1>Vorläufige Mitgliedsnummer</h1>

<p>Der Mitgliedschafstsantrag ist bei uns eingegangen.</p>

<p>Ihre vorläufige Mitgliedsnummer lautet: {{mitgliedsnummer}}</p>

<p>Bitte überweisen Sie den Mitgliedsbeitrag für das laufende Jahr in Höhe
von {{mitgliedsbeitrag}} € auf das im <a href="https://alumni.bwinf.de/wiki/impressum">Impressum</a> angegebene Konto. Sobald wir Ihre Zahlung
registriert haben, senden wir Ihnen Ihre persönlichen Zugangsdaten für
den Mitgliederbereich unserer Homepage zu.<p>

<p>Wir haben die Zahlungsdaten auch an Ihre angegeben E-Mailadresse gesandt.</p>

<p>Bitte auf der Überweisung unbedingt die Mitgliedsnummer „{{mitgliedsnummer}}“
angeben, da wir sonst die Zahlung nicht zuordnen können!</p>

<p><a href="/">Zur Startseite</a></p>